project:
  type: book
  output-dir: docs

book:
  title: "SCALES_Lab_Handbook"
  author: "William Murrah"
  date: "4/12/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - conferences.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



